services:
  postgres:
    image: postgres:9.5
    container_name: legacy_db
    environment:
      POSTGRES_DB: "applec"
      POSTGRES_USER: "anyway"
      POSTGRES_PASSWORD: "anyway"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  tomcat:
    image: tomcat:9.0-jdk17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=password
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8585:8080"
      - "5005:5005"
    volumes:
      - ./tomcat-cache:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs